// the most complete list i found

export const CSS_COLOR_NAMES = [
  "Blue",
  "Brown",
  "BurlyWood",
  "Cyan",
  "DarkBlue",
  "DarkCyan",
  "DarkGray",
  "DarkGrey",
  "DarkGreen",
  "DarkKhaki",
  "DarkMagenta",
  "DarkOliveGreen",
  "DarkOrange",
  "DarkOrchid",
  "DarkRed",
  "DarkSalmon",
  "DarkSlateBlue",
  "DarkSlateGray",
  "DarkSlateGrey",
  "DarkTurquoise",
  "DarkViolet",
  "DeepSkyBlue",
  "DimGray",
  "DimGrey",
  "DodgerBlue",
  "Gainsboro",
  "Gray",
  "Green",
  "Indigo",
  "LavenderBlush",
  "LawnGreen",
  "Magenta",
  "Maroon",
  "PowderBlue",
  "Purple",
  "RebeccaPurple",
  "Red",
  "RosyBrown",
  "RoyalBlue",
  "SaddleBrown",
  "Salmon",
  "SandyBrown",
  "Silver",
  "SteelBlue",
  "Thistle",
  "Turquoise",
  "Violet",
  "Wheat",
];

export const EMOJI_EXPRESSIONS = ["😂", "❤️ ", "👍", "😎", "👎","😇", "☠️ ", "😡", "😳"];
